# Generated by Django 2.0.4 on 2018-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Data_LogA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sump', models.FloatField()),
                ('Tank', models.FloatField()),
                ('Reservoir', models.FloatField()),
                ('time', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Data_LogB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sump', models.FloatField()),
                ('Tank', models.FloatField()),
                ('Reservoir', models.FloatField()),
                ('time', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Data_LogC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sump', models.FloatField()),
                ('Tank', models.FloatField()),
                ('Reservoir', models.FloatField()),
                ('time', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Data_LogD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sump', models.FloatField()),
                ('Tank', models.FloatField()),
                ('Reservoir', models.FloatField()),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
